import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<link rel="icon" type="image/x-icon" href="/app/Union.ico"></link>

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GymsEngine",
  description: "Generated by Sudip",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
